### ISSUE TITLE
"Error: Schema [object Object] is not valid" after upgrade to 1.0.0

### ISSUE THREAD

**Issue by Koblaid** [crissdev/gulp-yaml#4]
I get the error "Error: Schema [object Object] is not valid" after the upgrade to 1.0.0

If it is of any help the `[object Object]` in the error message looks like this:

```
{ include: 
   [ { include: [Object],
       implicit: [],
       explicit: [],
       compiledImplicit: [Object],
       compiledExplicit: [Object],
       compiledTypeMap: [Object] } ],
  implicit: 
   [ { tag: 'tag:yaml.org,2002:timestamp',
       kind: 'scalar',
       resolve: [Function: resolveYamlTimestamp],
       construct: [Function: constructYamlTimestamp],
       instanceOf: [Function: Date],
       predicate: null,
       represent: [Function: representYamlTimestamp],
       defaultStyle: null,
       styleAliases: {} },
     { tag: 'tag:yaml.org,2002:merge',
       kind: 'scalar',
       resolve: [Function: resolveYamlMerge],
       construct: [Function],
       instanceOf: null,
       predicate: null,
       represent: null,
       defaultStyle: null,
       styleAliases: {} } ],
  explicit: 
   [ { tag: 'tag:yaml.org,2002:binary',
       kind: 'scalar',
...
```

**Comment by crissdev** [comment]
@Koblaid Are you trying to pass an object to `schema` option, instead of a string?

If you provide the `schema` option the it must be passed as string, ie: `gulp.yaml({ schema: 'JSON_SCHEMA' })` or `gulp.yaml({ schema: 'json_schema' })`.

**Comment by Koblaid** [comment]
@crissdev No, we don't use `schema` at all.

We use it like this:

```
.pipe(plugins.yaml({ space: 2 }))
```

**Comment by crissdev** [comment]
Thanks. I can see where the problem is. Going to publish a fix in a few minutes.

**Comment by crissdev** [comment]
@Koblaid Just published a new version `1.0.1`. Can you confirm this issue is gone, please? Thanks.

**Comment by Koblaid** [comment]
Yes, it works. Thanks a lot! What a response time... :-D

**Comment by crissdev** [comment]
Great, thanks.
