### ISSUE TITLE
Error: duplicated mapping key at line

### ISSUE THREAD

**Issue by AlexanderKozhevin** [crissdev/gulp-yaml#5]
How to fix this problem? I don't have duplicating keys.

**Comment by crissdev** [comment]
@AlexanderKozhevin Can you give more info about your issue? If possible, please provide some code to reproduce this issue.

**Comment by AlexanderKozhevin** [comment]
Bloody sorry. It was really my fault.

**Comment by crissdev** [comment]
No problem.
